### ISSUE TITLE
Psionic Classes Don't Print the First Sheet

### ISSUE THREAD

**Issue by AnonJr** [marcusatbang/charactersheets-website#2] opened 2015-09-08 22:30 UTC
Trying to generate sheets for a Psion and Soulknife both end up missing the first page with the base abilities and skills. The rest of the sheets appear as normal.

**Comment by marcus-downing** [comment] 2015-09-10 16:57
Thanks (both for filing a moving it). I'm aware of the problem, and plan to fix it in the next version.

The problem is related to the change in the way skills are written. Previously there was a fixed list of skills printed on the page, and the Psionic classes got their own version of the page with a few extra skills on it. Also classes like the Barbarian got their own version of the page with an extra column for skills you can't use during rage. This meant that if you tried to multiclass say a Soulknife+Barbarian, it would only be able to pick _one_ of these versions of the front page to give you.

The new method has fewer versions of the page, because the skills are instead written at the point you download it, including class-specific Knowledge skills as well as extra skills like Autohypnosis, Psicraft and Knowledge (psionics). However, I should have make sure all trace of the custom sheet was excised from the data.

**Closed as completed** 2016-09-17 22:43 UTC
Labels: bug
